version: "3.9"

services:

  mongo:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: mongo
    environment:
      MONGO_DATABASE: testic
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - '27017:27017'

  nats:
    image: nats:2.9.23
    container_name: nats
    ports:
      - "4222:4222"
